### ISSUE TITLE
TLS setup throws AttributeError exception

### ISSUE THREAD

**Issue by spudlyo** [jobec/rfc5424-logging-handler#29]
Hi there. I'm running Python 3.6 in a virtual environment. Here is my simple test program that demonstrates the bug.
```
import logging
import socket
from rfc5424logging import Rfc5424SysLogHandler

logger = logging.getLogger('syslogtest')
logger.setLevel(logging.INFO)

sh = Rfc5424SysLogHandler(
    address=('127.0.0.1', 6514),
    tls_enable=True,
    tls_verify=True,
    socktype=socket.SOCK_STREAM,
    tls_ca_bundle="/etc/pki/CA/certs/ca-certs.pem"
)

logger.addHandler(sh)
```
Here is the traceback when running.
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    tls_ca_bundle="/etc/pki/CA/certs/ca-certs.pem"
  File "/home/spud/clean/venv/lib/python3.6/site-packages/rfc5424logging/handler.py", line 228, in __init__
    self._setup_transport()
  File "/home/spud/clean/venv/lib/python3.6/site-packages/rfc5424logging/handler.py", line 241, in _setup_transport
    self.tls_client_cert, self.tls_client_key, self.tls_key_password
  File "/home/spud/clean/venv/lib/python3.6/site-packages/rfc5424logging/transport.py", line 79, in __init__
    super(TLSSocketTransport, self).__init__(address, timeout, framing=framing)
  File "/home/spud/clean/venv/lib/python3.6/site-packages/rfc5424logging/transport.py", line 26, in __init__
    self.open()
  File "/home/spud/clean/venv/lib/python3.6/site-packages/rfc5424logging/transport.py", line 89, in open
    purpose=ssl.Purpose.SERVER_AUTH, cafile=self.tls_ca_bundle
AttributeError: 'TLSSocketTransport' object has no attribute 'tls_ca_bundle'
```

**Comment by jobec** [comment]
Fixed
